[tools]
go = "latest"
node = "latest"
python = "latest"
ruby = "latest"

aws-cli = "latest"
aws-vault = "latest"
fzf = "latest"
jq = "latest"
ghq = "latest"

"npm:ccusage" = "latest"
"npm:git-split-diffs" = "latest"
"npm:yarn" = "latest"
"npm:@openai/codex" = "latest"
